[workspace]
resolver = "2"
members = [
    "examples/cube",
    "examples/gltf",
    "examples/imgui",
    "examples/scene-viewer",
    "rend3",
    "rend3-gltf",
]

[profile.release]
debug = true
lto = "thin"

[patch.'https://github.com/gfx-rs/naga.git']
naga = { path = "../naga" }


[patch.'https://github.com/gfx-rs/wgpu.git']
wgpu = { path = "../wgpu/wgpu" }