[workspace]
members = [
    "examples/cube",
    "examples/gltf",
    "examples/imgui",
    "examples/scene-viewer",
    "rend3",
    "rend3-gltf",
    "rend3-list"
]

[profile.release]
debug = true
lto = "thin"
