[workspace]
resolver = "2"
members = [
    "examples/cube",
    "examples/gltf",
    "examples/scene-viewer",
    "rend3",
    "rend3-gltf",
    "rend3-pbr",
    "rend3-types"
]

[profile.release]
debug = true
lto = "thin"

[patch.crates-io]
# wgpu = { path = "../wgpu/wgpu" }
# wgpu-types = { path = "../wgpu/wgpu-types" }
# naga = { path = "../naga" }