[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "Unlicense",
]
copyleft = "allow"

[bans]
multiple-versions = "deny"
wildcards = "allow"
skip = [
    # everything
    { name = "cfg-if", version = "0.1.10" },
    # range-alloc
    { name = "range-alloc", version = "0.1.1" },
    # tracing-futures
    { name = "pin-project", version = "0.4.27" },
    { name = "pin-project-internal", version = "0.4.27" }
]

[advisories]
vulnerability = "warn"
unmaintained = "warn"
ignore = [
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
