[config]
default_to_workspace = false

[tasks.shaders]
script_runner = "@shell"
script = '''
glslc rend3/shaders/src/blit.vert -g -o rend3/shaders/spirv/blit.vert.spv
glslc rend3/shaders/src/blit.frag -g -o rend3/shaders/spirv/blit.frag.spv
glslc rend3/shaders/src/cull.comp -g -o rend3/shaders/spirv/cull.comp.spv
glslc rend3/shaders/src/depth.vert -DCPU_MODE -g -o rend3/shaders/spirv/depth.vert.cpu.spv
glslc rend3/shaders/src/depth.frag -DCPU_MODE -g -o rend3/shaders/spirv/depth.frag.cpu.spv
glslc rend3/shaders/src/depth.vert -DGPU_MODE -g -o rend3/shaders/spirv/depth.vert.gpu.spv
glslc rend3/shaders/src/depth.frag -DGPU_MODE -g -o rend3/shaders/spirv/depth.frag.gpu.spv
glslc rend3/shaders/src/opaque.vert -DCPU_MODE -g -o rend3/shaders/spirv/opaque.vert.cpu.spv
glslc rend3/shaders/src/opaque.frag -DCPU_MODE -g -o rend3/shaders/spirv/opaque.frag.cpu.spv
glslc rend3/shaders/src/opaque.vert -DGPU_MODE -g -o rend3/shaders/spirv/opaque.vert.gpu.spv
glslc rend3/shaders/src/opaque.frag -DGPU_MODE -g -o rend3/shaders/spirv/opaque.frag.gpu.spv
glslc rend3/shaders/src/skybox.vert -g -o rend3/shaders/spirv/skybox.vert.spv
glslc rend3/shaders/src/skybox.frag -g -o rend3/shaders/spirv/skybox.frag.spv
'''