[package]
name = "rend3-types"
version = "0.0.5"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
description = "Type definitions for rend3"
readme = "../README.md"
repository = "https://github.com/BVE-Reborn/rend3"
license = "MIT OR Apache-2.0 OR Zlib"
keywords = ["3d", "graphics", "gpu", "renderer", "wgpu"]
categories = ["game-development", "graphics", "rendering", "rendering::engine"]


[dependencies]
bitflags = "1"
glam = { version = "0.17" }
wgt = { package = "wgpu-types", version = "0.9", git = "https://github.com/gfx-rs/wgpu.git", rev = "a222e6eb11dc6520414b2eb2f9a9604c3f2d3620" }
