[package]
name = "rend3-types"
version = "0.0.6"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
description = "Type definitions for rend3"
readme = "../README.md"
repository = "https://github.com/BVE-Reborn/rend3"
license = "MIT OR Apache-2.0 OR Zlib"
keywords = ["3d", "graphics", "gpu", "renderer", "wgpu"]
categories = ["game-development", "graphics", "rendering", "rendering::engine"]


[dependencies]
bitflags = "1"
glam = { version = "0.18" }
wgt = { package = "wgpu-types", version = "0.10" }
