[package]
name = "rend3-scene-viewer-example"
license = "MIT OR Apache-2.0 OR Zlib"
version = "0.0.6"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
publish = false

[[bin]]
name = "scene-viewer"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basis = { version = "0.1.0", git = "https://github.com/BVE-Reborn/basis-rs.git", rev = "17480940261db81877ce4fec983a18a39d7db633" }
env_logger = { version = "0.9", default-features = false, features = ["termcolor", "atty"] }
fnv = "1"
glam = "0.17"
image = { version = "0.23", default-features = false, features = ["png", "jpeg", "tiff"]}
histogram = "0.6"
pico-args = "0.4"
pollster = "0.2"
rend3 = { path = "../../rend3" }
rend3-gltf = { path = "../../rend3-gltf" }
rend3-pbr = { path = "../../rend3-pbr" }
smallvec = "1"
winit = "0.25"

