[package]
name = "rend3"
version = "0.1.0"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
description = "Asynchronous renderer made for capstone"
readme = "README.md"
repository = "https://github.com/cwfitzgerald/capstone"
license = "MPL-2.0"
keywords = []
categories = []

[dependencies]
bitflags = "1"
bytemuck = "1"
glam = "0.9"
imgui = "0.4"
imgui-wgpu = "0.9"
indexmap = "1"
fnv = "1"
parking_lot = "0.11"
raw-window-handle = "0.3"
range-alloc = "0.1"
shaderc = "0.6"
smallvec = "1"
thiserror = "1"
wgpu = "0.6"
wgpu-conveyor = "0.1"
wgpu-subscriber = "0.1"
winit = { git = "https://github.com/rust-windowing/winit.git", rev = "c1ea0dde92e1de9e029e7fbb2485a454aa81b918",  default-features = false, features = ["x11"] }
