[package]
name = "rend3-gltf"
version = "0.1.0"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
description = "gltf scene and model loader for rend3"
repository = "https://github.com/BVE-Reborn/rend3"
license = "MPL-2.0"
keywords = []
categories = []

[dependencies]
gltf = { version = "0.15", features = ["KHR_lights_punctual", "KHR_materials_unlit"] }
rend3 = { version = "0.1", path = "../rend3" }
