name: CI

on:
  push:
    branches: ["trunk", "CI/**"]
  pull_request:

env:
  RUSTFLAGS: --cfg=web_sys_unstable_apis -D warnings

jobs:
  build:
    timeout-minutes: 30

    strategy:
      matrix:
        include:
          # wasm 1.57
          - name: '1.57 wasm'
            os: 'ubuntu-latest'
            target: 'wasm32-unknown-unknown'
            rust_version: '1.57'

          # native 1.57
          - name: '1.57 linux'
            os: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-gnu'
            rust_version: '1.57'
          - name: '1.57 mac'
            os: 'macos-latest'
            target: 'x86_64-apple-darwin'
            rust_version: '1.57'
          - name: '1.57 windows'
            os: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            rust_version: '1.57'
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust toolchain
        id: setup-rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust_version }}
          target: ${{ matrix.target }}
          components: clippy
          default: true
          override: true

      - name: caching
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.target }}-a # suffix for cache busting

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
        if: matrix.target != 'wasm32-unknown-unknown'

      - name: build (no imgui)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --workspace --exclude rend3-imgui --exclude rend3-imgui-example
        if: matrix.target == 'wasm32-unknown-unknown'

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target }}
        if: matrix.target != 'wasm32-unknown-unknown'

      - name: clippy (rend3-gltf featureless)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target }} -p rend3-gltf --no-default-features

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target }}
        if: matrix.target != 'wasm32-unknown-unknown'

      - name: clippy (no imgui)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target }} --workspace --exclude rend3-imgui --exclude rend3-imgui-example
        if: matrix.target == 'wasm32-unknown-unknown'

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust toolchain
        id: setup-rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          default: true
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          log-level: warn
          command: check
          arguments: --all-features
